"use client";
import * as html2pdf from "html2pdf.js";
import { useForm } from "react-hook-form";
import PDFPreview from "../PDFPreview";

const IMAGEDIMENSIONS = { width: 754, height: 387 };
const PDFTEXT = "Thank you for supporting us";

export default function ThankYouForm() {
  // custom message generator
  function customPDFText(
    baseText: string,
    firstName: string,
    lastName: string
  ) {
    if (firstName || lastName) {
      return baseText + ", " + firstName + " " + lastName + "!";
    }
    return baseText + "!";
  }

  // instantiate form, controlled inputs, handle submit
  const { register, handleSubmit, watch } = useForm();

  const onSubmit = () => generatePDF();

  async function generatePDF() {
    const pdfPreviewElement = document.getElementById("pdf-preview");

    if (pdfPreviewElement) {
      const options = {
        jsPDF: {
          unit: "px",
          format: [
            pdfPreviewElement.offsetWidth,
            pdfPreviewElement.offsetHeight,
          ],
          orientation: "l",
          hotfixes: ["px_scaling"],
          compress: true,
        },
      };

      // have to delete extra page generated by html2canvas
      html2pdf()
        .set(options)
        .from(pdfPreviewElement)
        .toPdf()
        .get("pdf")
        .then((pdf) => {
          const totalPages = pdf.internal.getNumberOfPages();
          if (totalPages > 1) {
            pdf.deletePage(totalPages);
          }
          pdf.save("anima-thank-you.pdf");
        });
    }
  }

  return (
    <>
      <PDFPreview
        width={IMAGEDIMENSIONS.width}
        height={IMAGEDIMENSIONS.height}
        pdfText={customPDFText(PDFTEXT, watch("firstName"), watch("lastName"))}
      />
      <form
        className="mt-8 grid gap-4 sm:grid-cols-3 items-end"
        onSubmit={handleSubmit(onSubmit)}
      >
        <label className="block text-sm  text-[var(--accent-grey)]">
          First name:
          <input
            type="text"
            className="mt-2 w-full rounded-sm bg-white shadow-sm ring-1 ring-slate-200 focus:ring-2 focus:ring-cyan-500/60 focus:outline-none px-5 py-3 placeholder:text-slate-400  text-[var(--accent-grey)]"
            placeholder="John"
            aria-label="First name"
            {...register("firstName")}
          />
        </label>
        <label className="block text-sm  text-[var(--accent-grey)]">
          Last name:
          <input
            type="text"
            className="mt-2 w-full rounded-sm bg-white shadow-sm ring-1 ring-slate-200 focus:ring-2 focus:ring-cyan-500/60 focus:outline-none px-5   py-3 placeholder:text-slate-400  text-[var(--accent-grey)]"
            placeholder="Doe"
            aria-label="Last name"
            {...register("lastName")}
          />
        </label>
        <button
          type="submit"
          className="mt-6 sm:mt-0 inline-flex items-center justify-center rounded-sm px-6 py-3 text-base font-semibold text-white
           bg-gradient-to-r from-cyan-500 to-sky-600 shadow-lg shadow-cyan-500/20
           ring-1 ring-inset ring-white/10
           hover:from-cyan-600 hover:to-sky-700
           focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-offset-2 focus-visible:ring-cyan-500"
        >
          Download PDF
        </button>
      </form>
    </>
  );
}
